# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='node_type',
            field=models.CharField(choices=[('\u603b\u90e8', '\u603b\u90e8'), ('\u5206\u90e8', '\u5206\u90e8')], max_length=50, verbose_name='\u8282\u70b9\u7c7b\u578b'),
        ),
    ]
