# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0002_auto_20160224_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='signer',
            new_name='node_signer',
        ),
    ]
