# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0003_auto_20160224_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_caption', models.CharField(max_length=100, verbose_name='\u8bbe\u5907\u540d\u79f0')),
                ('device_serial', models.CharField(max_length=100, verbose_name='\u8bbe\u5907\u5e8f\u5217\u53f7')),
                ('device_type', models.CharField(max_length=50, verbose_name='\u8bbe\u5907\u578b\u53f7')),
                ('device_vendor', models.CharField(choices=[('CISCO', 'CISCO'), ('JUNIPER', 'JUNIPER'), ('TOPSEC', 'TOPSEC'), ('HUAWEI', 'HUAWEI'), ('H3C', 'H3C')], max_length=50, verbose_name='\u8bbe\u5907\u5382\u5546')),
                ('device_remark', models.CharField(blank=True, max_length=50, verbose_name='\u5907\u6ce8')),
                ('device_ip', models.GenericIPAddressField(verbose_name='\u7ba1\u7406IP')),
                ('device_status', models.CharField(default='\u542f\u7528', max_length=10, verbose_name='\u8bbe\u5907\u72b6\u6001')),
                ('signer', models.CharField(default='system', max_length=30, verbose_name='\u767b\u8bb0\u4eba')),
                ('device_signtime', models.DateField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='echo.Node')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_code', models.CharField(max_length=100, verbose_name='\u7ebf\u8def\u7f16\u53f7')),
                ('line_local', models.CharField(default='\u4e0a\u6d77\u6570\u636e\u4e2d\u5fc3', max_length=50, verbose_name='\u6240\u5728\u673a\u623f')),
                ('line_speed', models.CharField(choices=[('2M', '2M'), ('4M', '4M'), ('6M', '6M'), ('10M', '10M'), ('\u5176\u4ed6', '\u5176\u4ed6')], default='6M', max_length=10, verbose_name='\u7ebf\u8def\u901f\u7387')),
                ('line_spname', models.CharField(choices=[('\u4e2d\u56fd\u7535\u4fe1', '\u4e2d\u56fd\u7535\u4fe1'), ('\u4fe1\u7f51\u516c\u53f8', '\u4fe1\u7f51\u516c\u53f8'), ('\u4e2d\u56fd\u8054\u901a', '\u4e2d\u56fd\u8054\u901a'), ('\u4e2d\u56fd\u79fb\u52a8', '\u4e2d\u56fd\u79fb\u52a8'), ('\u4e2d\u56fd\u94c1\u901a', '\u4e2d\u56fd\u94c1\u901a'), ('\u5176\u4ed6', '\u5176\u4ed6')], default='\u4fe1\u7f51\u516c\u53f8', max_length=10, verbose_name='\u8fd0\u8425\u5546')),
                ('line_type', models.CharField(choices=[('MSTP', 'MSTP'), ('MSAP', 'MASP'), ('SDH', 'SDH'), ('DIAL', 'DIAL'), ('\u5176\u4ed6', '\u5176\u4ed6')], default='MSTP', max_length=50, verbose_name='\u7ebf\u8def\u7c7b\u578b')),
                ('line_status', models.BooleanField(default=True, verbose_name='\u7ebf\u8def\u542f\u7528')),
                ('line_open', models.DateField(verbose_name='\u5f00\u901a\u65f6\u95f4')),
                ('line_closed', models.DateField(blank=True, null=True, verbose_name='\u5173\u95ed\u65f6\u95f4')),
                ('signer', models.CharField(default='system', max_length=30, verbose_name='\u767b\u8bb0\u4eba')),
                ('line_signtime', models.DateField(auto_now_add=True)),
                ('line_remarks', models.CharField(blank=True, max_length=255, verbose_name='\u5907\u6ce8')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='echo.Node')),
            ],
        ),
    ]
