# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 03:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0004_device_line'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='signer',
            new_name='device_signer',
        ),
        migrations.RenameField(
            model_name='line',
            old_name='signer',
            new_name='line_signer',
        ),
    ]
