# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0006_auto_20160311_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='line_status',
        ),
    ]
