# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0007_remove_line_line_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='line_status',
            field=models.BooleanField(default=True, verbose_name='\u7ebf\u8def\u542f\u7528'),
        ),
    ]
