# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-13 08:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('echo', '0008_line_line_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsibility', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_content', models.TextField(blank=True)),
                ('process_signtime', models.DateTimeField(auto_now_add=True)),
                ('process_signer', models.CharField(default='system', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_code', models.CharField(default='error_code', max_length=30)),
                ('task_title', models.CharField(max_length=100, verbose_name='\u4efb\u52a1\u540d\u79f0')),
                ('task_category', models.CharField(choices=[('\u7efc\u5408\u4e8b\u52a1', '\u7efc\u5408\u4e8b\u52a1'), ('\u673a\u6784\u5efa\u8bbe', '\u673a\u6784\u5efa\u8bbe'), ('\u7ebf\u8def\u4e8b\u52a1', '\u7ebf\u8def\u4e8b\u52a1')], default='\u7efc\u5408\u4e8b\u52a1', max_length=100, verbose_name='\u4efb\u52a1\u5206\u7c7b')),
                ('task_contacts', models.TextField(blank=True, verbose_name='\u8054\u7cfb\u4eba')),
                ('task_status', models.CharField(default='\u5904\u7406\u4e2d', max_length=20, verbose_name='\u5904\u7406\u4e2d')),
                ('task_signer', models.CharField(default='system', max_length=30)),
                ('task_signtime', models.DateField(auto_now_add=True)),
                ('task_member', models.ManyToManyField(to='echo.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_title', models.CharField(max_length=255)),
                ('upload_path', models.CharField(max_length=255)),
                ('upload_signtime', models.DateTimeField(auto_now_add=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='echo.Task')),
            ],
        ),
        migrations.AddField(
            model_name='process',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='echo.Task'),
        ),
    ]
